language: python
python:
  - '3.4'
install: pip install -r requirements.txt 
script: python manage.py test --settings=beyonic_portal.settings.test

before_script:
  # To run tests requiring a graphical user interface, e.g. a web browser, do the following
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
